name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1.8.0
    - name: Build Engine
      run: make /f Makefile.engine.windows.mak all
    - name: Build Game
      run: make /f Makefile.testbed.windows.mak all
