name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        choco install llvm
        choco install make
      shell: pwsh

    - name: Set Environment Variables
      run: |
        echo "VULKAN_SDK=$Env:VULKAN_SDK" >> $Env:GITHUB_ENV
      shell: pwsh

    - name: Build Engine
      run: |
        echo "Building the engine..."
        make -f "Makefile.engine.windows.mak" all
      shell: cmd
